name: Sample Pipeline_1682014843949
stages:
  - name: build
    spec:
      steps:
        - name: echo
          spec:
            run: echo hello world
          type: script
    type: ci
version: 1
